### ISSUE TITLE
Demo link not working 

### ISSUE THREAD

**Issue by LakshmanKishore** [google/ml-compiler-opt#181]
The demo link provided in the README.md is not working.

**Comment by LakshmanKishore** [comment]
I can fix this issue by replacing the demo link.
I have found 5 demo links 

1. README.md 2 demo links
2. Contributing.md 1 demo link
3. adding_features.md 2 demo links

Should I need to replace all the demo link to the [inlining-demo](https://github.com/google/ml-compiler-opt/tree/main/docs/inlining-demo/demo.md) or [regalloc-demo](https://github.com/google/ml-compiler-opt/tree/main/docs/regalloc-demo/demo.md) ?

**Comment by yundiqian** [comment]
thanks for bringing up the issue and thanks for the fixing!
