### ISSUE TITLE
【QUESTION】How to train an inline model with our own code?

### ISSUE THREAD

**Issue by 18liumin** [google/ml-compiler-opt#314]

**Comment by mtrofin** [comment]
See the examples under `docs`, while they are specific to Fuchsia or chrome, they go through corpus extraction as a fairly early step.

High-level, assuming your project is cmake based:
- you add to your cmake command line `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON`
- build your project
- run `compiler_opt/tools/extract_ir.py` (see [this](https://github.com/google/ml-compiler-opt/blob/main/docs/inlining-demo/demo.md#extract-the-corpus) for example - you may want to drop the `--cmd_filter`)
- the rest of the steps (i.e. [Collect Trace and Generate Vocab](https://github.com/google/ml-compiler-opt/blob/main/docs/inlining-demo/demo.md#collect-trace-and-generate-vocab)) are only dependent on the corpus and not on the specifics of your project.

**Comment by Colibrow** [comment]
A long time ago, I trained a model for my projects, here is the gist when training [gist](https://gist.github.com/Colibrow/9d2b31bc7eff127cfe74c807fce86451) Hope it helps.

**Comment by 18liumin** [comment]
why ninja toolchain-distribution
ninja: error: unknown target 'toolchain-distribution
DESTDIR=${LLVM_INSTALLDIR} ninja install-toolchain-distribution-stripped

**Comment by Colibrow** [comment]
> why ninja toolchain-distribution ninja: error: unknown target 'toolchain-distribution DESTDIR=${LLVM_INSTALLDIR} ninja install-toolchain-distribution-stripped

maybe some of these dependencies were missed, it's been a long time.
