### ISSUE TITLE
【BUG】clang (LLVM option parsing): Unknown command line argument '-tfutils-use-simplelogger'

### ISSUE THREAD

**Issue by 18liumin** [google/ml-compiler-opt#315]

**Comment by mtrofin** [comment]
how did you build clang, are you sure it has tflite linked?

**Comment by 18liumin** [comment]
> how did you build clang, are you sure it has tflite linked?

cmake -S llvm -B build -G Ninja -DLLVM_ENABLE_LTO=OFF -DCMAKE_INSTALL_PREFIX=${LLVM_INSTALLDIR} -DLLVM_ENABLE_PROJECTS="clang;lld" -DTENSORFLOW_C_LIB_PATH=${TENSORFLOW_C_LIB_PATH} -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=On -DLLVM_TARGETS_TO_BUILD="X86;AArch64" -C ${TFLITE_PATH}/tflite.cmake

**Comment by mtrofin** [comment]
-DTENSORFLOW_C_LIB_PATH  and -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=On aren't required anymore, so just the -C ${TFLITE_PATH}/tflite.cmake should be enough. Can you test that TFLiteUtils.cpp is compiled?

fwiw, -tfutils-use-simplelogger is also not needed anymore, and you can yank it out of the place it's passed in compilation_runner.py, but regardless, there seems to be an issue with the build not appearing to pick TFLiteUtils.cpp.

**Comment by 18liumin** [comment]
> TFLiteUtils.cpp
My llvm-project does not have TFLiteUtils.cpp file,  Because  the branch was switched :  git checkout fa4c3f70ff0768a270b0620dc6d158ed1205ec4e

**Comment by 18liumin** [comment]
> -DTENSORFLOW_C_LIB_PATH and -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=On aren't required anymore, so just the -C ${TFLITE_PATH}/tflite.cmake should be enough. Can you test that TFLiteUtils.cpp is compiled?
> 
> fwiw, -tfutils-use-simplelogger is also not needed anymore, and you can yank it out of the place it's passed in compilation_runner.py, but regardless, there seems to be an issue with the build not appearing to pick TFLiteUtils.cpp.

My llvm-project does not have TFLiteUtils.cpp file, Because the branch was switched : git checkout fa4c3f70ff0768a270b0620dc6d158ed1205ec4e

**Comment by boomanaiden154** [comment]
You should probably just build with `main`. That commit is pretty out of date at this point and that line should probably be removed from the demo, or a more recent commit at least should be put up.
