### ISSUE TITLE
【Question】Can you open the code of ES algorithm?

### ISSUE THREAD

**Issue by 18liumin** [google/ml-compiler-opt#320]
The training method: instead of PPO, we used ES [*] (which is unfortunately not currently open sourced). This does not change the format of the saved model, but we found that this training method was easier to scale to accommodate the larger corpus.

**Comment by boomanaiden154** [comment]
The code for ES is already open under `./compiler_opt/es`. There isn't a lot of documentation on how to use it, but it is out there. There was an issue already opened to release the code (https://github.com/google/ml-compiler-opt/issues/248) that has pretty much been completed at this point.

**Comment by mtrofin** [comment]
Yup, #248 was basically completed by @salaast, there are a few touchups left. If you're eager to try it out, you can look at https://github.com/mtrofin/ml-compiler-opt/tree/es (it's work in progress for inlining for speed, but you should be able to derive what you need for ES). I plan to merge that at a point, of course.
