### ISSUE TITLE
questions about feature log

### ISSUE THREAD

**Issue by 18liumin** [google/ml-compiler-opt#324]
result = log_reader.read_log_as_sequence_examples(log_path)
    if len(result) != 1:
      return {}

Why does this code need to determine the  “if len(result) != 1”?

**Comment by mtrofin** [comment]
I'm going to assume this is [here](https://github.com/google/ml-compiler-opt/blob/0f895e325491793efbc45a1675f9a71f7c8c4f9e/compiler_opt/rl/inlining/inlining_runner.py#L112). Inlining is treated as a module-wide problem, as opposed to for example regalloc which is per-function. So for the whole problem, we expect to get at most 1 trace. We may get 0 traces for corner-case modules that trigger no inlining decisions - like a module with 1 function, or functions that have no call sites, or callsites to functions defined in other modules, exclusively.

**Comment by 18liumin** [comment]
> I'm going to assume this is [here](https://github.com/google/ml-compiler-opt/blob/0f895e325491793efbc45a1675f9a71f7c8c4f9e/compiler_opt/rl/inlining/inlining_runner.py#L112). Inlining is treated as a module-wide problem, as opposed to for example regalloc which is per-function. So for the whole problem, we expect to get at most 1 trace. We may get 0 traces for corner-case modules that trigger no inlining decisions - like a module with 1 function, or functions that have no call sites, or callsites to functions defined in other modules, exclusively.

  if len(result) != 1:
      return {}
    sequence_example = next(iter(result.values()))

Why only get the trajectory of one caller-callee feature in the cpp file?
