### ISSUE TITLE
Where do I find pretrained models for MLGOPerf?

### ISSUE THREAD

**Issue by Nirhar** [google/ml-compiler-opt#338]
Hey!

I was interested in trying out your models for MLGOPerf for my use case, where do I find them, if they've been published?

Also any resources on how I can train my own models for MLGOPerf would be helpful!

**Comment by mtrofin** [comment]
I replied on the llvm-mlgo group thread.

**Comment by Nirhar** [comment]
Thanks, I missed that message!
Also, do you have any pretrained models in MLGOPerf for Inlining for Performance?

**Comment by boomanaiden154** [comment]
MLGOPerf is a separate work, none of which has been open sourced at this point (to my knowledge). The authors did express interest in open sourcing the models, but that was a while ago and I haven't seen any updates.

**Comment by Nirhar** [comment]
Thanks for the clarification1
