### ISSUE TITLE
How the inlining in the compiled project is identified

### ISSUE THREAD

**Issue by island255** [google/ml-compiler-opt#40]
Hi, I have read your paper "MLGO: a Machine Learning Guided Compiler Optimizations Framework" and some questions have come to me. 

The paper writes, "we train the warmstart policy to imitate the heuristic inlining decisions in LLVM using behavioral cloning algorithm". I am curious how the ground truth of inlining is identified in the compiled projects. 

I noticed that the projects are compiled to emit bitcode. Is the debug information in it reflecting the inlining? If so, could you introduce how it is identified in the bitcode？ And can the inlining in a linked binary be identified this way?

**Comment by yundiqian** [comment]
Thanks for the interest in our paper!

The information of heuristic inlining decisions is not decoded from the bitcode. we write an extra log file in the format of a TensorFlow SequenceExample protobuf to store these informations during compilation, and we read the log file after the compilation to fetch the information https://github.com/google/ml-compiler-opt/blob/d13b1ef30f6fc596e7af0279cd19105f3e3c5faa/compiler_opt/rl/inlining/inlining_runner.py#L123

@mtrofin can point you more details on how the log file is written during inlining.

**Comment by mtrofin** [comment]
The logging happens here: https://github.com/llvm/llvm-project/blob/main/llvm/lib/Analysis/DevelopmentModeInlineAdvisor.cpp#L311

**Comment by island255** [comment]
Got it! I will look into it. Thanks for your reply.
