### ISSUE TITLE
Compiling LLVM meets the problem: error: use of undeclared identifier '__sanitizer_get_configuration'

### ISSUE THREAD

**Issue by island255** [google/ml-compiler-opt#44]
Hi, I follow the instructions in demo.md and try to replicate the process of training a model. But I meet an error when compiling LLVM. 

I am using the release package ml-compiler-opt-inlining-Oz-v1.1 and trying to replicate it in ubuntu 20:04 several times. The error always comes out. Here is the full error message:

```
/home/xx/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_fuchsia.cpp:410:24: error: use of undeclared identifier '__sanitizer_get_configuration'
  zx_status_t status = __sanitizer_get_configuration(file_name, &vmo);
                       ^
1 error generated.

...

ninja: build stopped: subcommand failed.
FAILED: runtimes/runtimes-x86_64-unknown-fuchsia-stamps/runtimes-x86_64-unknown-fuchsia-build 
```
The LLVM is set to the commit fa4c3f70ff0768a270b0620dc6d158ed1205ec4e. And all instructions is running in a user mode. The  python version is 3.8.10. 

Is there any packages that I missed in this replication?

**Comment by island255** [comment]
By the way, do you have plans to release a docker image to facilitate replication? A docker image will be a great help for those who want to replicate this work.

**Comment by boomanaiden154** [comment]
It seems like you've just copied the LLVM commit that was used in the demo? If you did that, you also need to make sure that you run the following command:
```
jiri update -gc ~/ml-compiler-opt/docs/demo/fuchsia.xml
```
So that the Fuchsia version is actually compatible with that LLVM commit. Last time I looked at the inliner training code though, instead of pinning everything using that command, I just used Fuchsia at head and ran the following command:
```
jiri package 'fuchsia/third_party/clang/${platform}'
```
in order to get the clang commit that I then checked out LLVM to.

I've been meaning to write a shell script based on the demo that can be used to validate everything inside a fresh docker container, but I haven't done so yet. I might try and work on that later today.

**Comment by island255** [comment]
I use git to get the source code of LLVM and run checkout before compilation. Fuchsia is also changed to the corresponding version by using `jiri update ~/ml-compiler-opt/docs/demo/fuchsia.xml` before the compilation. But this error remains.

Then I have tried the following configurations: 

`cmake -G Ninja \
  -DLLVM_ENABLE_LTO=OFF \
  -DCMAKE_INSTALL_PREFIX= \
  -DTENSORFLOW_C_LIB_PATH=${TENSORFLOW_C_LIB_PATH} \
  -DPython3_EXECUTABLE=/usr/bin/python3 \
  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=On \
  -C ${LLVM_SRCDIR}/clang/cmake/caches/Fuchsia-stage2.cmake \
  ${LLVM_SRCDIR}/llvm`

The compilation of LLVM succeed. Thus the errors may come from the following setting:

`  -DLINUX_x86_64-unknown-linux-gnu_SYSROOT=${SYSROOT_DIR}/linux-x64 \
  -DLINUX_aarch64-unknown-linux-gnu_SYSROOT=${SYSROOT_DIR}/linux-arm64 \
  -DFUCHSIA_SDK=${IDK_DIR} \`

Here, I noticed the install of these package. 
```shell
cipd install fuchsia/sdk/core/linux-amd64 latest -root ${IDK_DIR}
cipd install fuchsia/sysroot/linux-arm64 latest -root ${SYSROOT_DIR}/linux-arm64
cipd install fuchsia/sysroot/linux-amd64 latest -root ${SYSROOT_DIR}/linux-x64
```
As I successes the compilation a few days ago, I wonder if the latest version of fuchsia has been changed so that the compilation failed.

**Comment by petrhosek** [comment]
`__sanitizer_get_configuration` was deprecated and removed from Fuchsia's C library which is part of the SDK. We should update the demo instructions to pin the version of the Fuchsia SDK and host sysroot CIPD packages rather than using `latest`.
